# Generated by Django 5.1.2 on 2024-11-18 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='forum_ref',
        ),
    ]
