# Generated by Django 5.1.1 on 2024-09-27 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votepost',
            name='user_ref',
        ),
    ]
