# Generated by Django 5.1.1 on 2024-09-27 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_votepost_user_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='votepost',
            name='user_ref',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
