# Generated by Django 5.1.1 on 2024-09-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_votecomment_votepost_delete_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, default='profile/blank-profile-picture-973460_128012234212.png', upload_to='profile/'),
        ),
    ]
