# Generated by Django 5.1.3 on 2024-11-28 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_reportpost_post_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('admin_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans_issued', to=settings.AUTH_USER_MODEL)),
                ('user_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
