# Generated by Django 5.1.3 on 2024-11-30 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_user_is_banned'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justification', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('userban_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.userban')),
            ],
        ),
    ]
